# Generated by Django 4.2.6 on 2023-10-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_protest_date_protest_image_protest_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protest',
            name='title',
            field=models.CharField(default='This is a Protest !', max_length=200),
        ),
    ]
