# Generated by Django 4.0.4 on 2022-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='preview',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/event_images'),
        ),
    ]
